services:
  degoog:
    container_name: Degoog
    image: ghcr.io/fccview/degoog:latest
    volumes:
      - /volume1/docker/degoog/data:/app/data
    ports:
      - "4444:4444"
    environment:
     PUID: 1026
     PGID: 100
     DEGOOG_PUBLIC_INSTANCE: false # true if proxy
     DEGOOG_SETTINGS_PASSWORDS: ${DEGOOG_SETTINGS_PASSWORDS}
    restart: on-failure:5
    networks:
      - group1

networks:
  searxng:
    name: group1