services:
  bentopdf:
    image: ghcr.io/alam00000/bentopdf:latest
    container_name: BentoPDF
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 8080 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    ports:
      - 3183:8080
    restart: on-failure:5
    networks:
      - group1

networks:
  group1:
    external: true  # Use an existing network