version: '3.9'
services:
  gotify:
    image: ghcr.io/gotify/server:latest
    container_name: Gotify
    restart: on-failure:5
    ports:
      - 6743:80
    volumes:
      - /volume1/docker/gotify:/app/data:rw
    environment:
      GOTIFY_DEFAULTUSER_NAME: ${GOTIFY_DEFAULTUSER_NAME}
      GOTIFY_DEFAULTUSER_PASS: ${GOTIFY_DEFAULTUSER_PASS}
      TZ: America/Los_Angeles  # Use your timezone
    networks:
      - group1

networks:
  group1:
    external: true  # Use an existing network