services:
  homebox:
    container_name: Homebox
    image: ghcr.io/sysadminsmedia/homebox:latest
    mem_limit: 3g
    cpu_shares: 1024
    security_opt:
      - no-new-privileges:true
    ports:
      - 3101:7745
    volumes:
      - /volume1/docker/homebox:/data:rw
    environment:
       HBOX_LOG_LEVEL: info
       HBOX_LOG_FORMAT: json  # This defaults as text and throws errors
       HBOX_WEB_MAX_UPLOAD_SIZE: 15
       TZ: America/Los_Angeles
       HBOX_OPTIONS_ALLOW_REGISTRATION: false  # Need true for first install
       HBOX_OIDC_ENABLED: ${HBOX_OIDC_ENABLED}
       HBOX_OIDC_ISSUER_URL: ${HBOX_OIDC_ISSUER_URL}
       HBOX_OIDC_CLIENT_ID: ${HBOX_OIDC_CLIENT_ID}
       HBOX_OIDC_CLIENT_SECRET: ${HBOX_OIDC_CLIENT_SECRET}
       HBOX_OPTIONS_TRUST_PROXY: ${HBOX_OPTIONS_TRUST_PROXY}
       HBOX_OIDC_VERIFY_EMAIL: ${HBOX_OIDC_VERIFY_EMAIL}
       HBOX_OIDC_AUTO_REDIRECT: ${HBOX_OIDC_AUTO_REDIRECT}
       HBOX_OPTIONS_ALLOW_LOCAL_LOGIN: ${HBOX_OPTIONS_ALLOW_LOCAL_LOGIN}
       HBOX_AUTH_RATE_LIMIT_MAX_ATTEMPTS: 2
    restart: on-failure:5
    networks:
      - group1

networks:
  group1:
    external: true  # Use an existing network