version: "3.9"
services:
  pwndrop:
    container_name: Pwndrop
    image: ghcr.io/linuxserver/pwndrop:latest
    security_opt:
      - no-new-privileges:false
      - seccomp:unconfined
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/8080' || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    environment:
     SECRET_PATH: /drop
     TZ: America/Los_Angeles  # Use your own timezone
     PUID: 1026  # Use your own
     PGID: 100  # Use your own
    volumes:
      - /volume1/docker/pwndrop:/config:rw
    ports:
      - 8048:8080
    restart: on-failure:5
    networks:
      - group1

networks:
  group1:
    external: true  # Use an existing network